export const MASTER_REMEDIES: string[] = [
  'Abrotanum',
  'Abies Canadensis',
  'Abies Nigra',
  'Acalypha Indica',
  'Aconitum Napellus',
  'Actaea Racemosa',
  'Adonis Vernalis',
  'Aesculus Hippocastanum',
  'Aethusa Cynapium',
  'Agaricus Muscarius',
  'Agnus Castus',
  'Ailanthus Glandulosa',
  'Allium Cepa',
  'Aloe Socotrina',
  'Alumina',
  'Ambra Grisea',
  'Ammonium Carbonicum',
  'Ammonium Muriaticum',
  'Anacardium Orientale',
  'Antimonium Crudum',
  'Antimonium Tartaricum',
  'Apis Mellifica',
  'Apocynum Cannabinum',
  'Argentum Metallicum',
  'Argentum Nitricum',
  'Arnica Montana',
  'Arsenicum Album',
  'Arsenicum Iodatum',
  'Arum Triphyllum',
  'Asafoetida',
  'Aurum Metallicum',
  'Bacillinum',
  'Baptisia Tinctoria',
  'Baryta Carbonicum',
  'Belladonna',
  'Bellis Perennis',
  'Berberis Vulgaris',
  'Borax',
  'Bovista',
  'Bromium',
  'Bryonia Alba',
  'Bufo Rana',
  'Cactus Grandiflorus',
  'Caladium Seguinum',
  'Calcarea Carbonicum',
  'Calcarea Fluoricum',
  'Calcarea Phosphoricum',
  'Calcarea Sulphurica',
  'Calendula Officinalis',
  'Camphora',
  'Cannabis Indica',
  'Cannabis Sativa',
  'Cantharis',
  'Capsicum Annuum',
  'Carbo Animalis',
  'Carbo Vegetabilis',
  'Carcinosin',
  'Caulophyllum',
  'Causticum',
  'Ceanothus Americanus',
  'Chamomilla',
  'Chelidonium Majus',
  'Chimaphila Umbellata',
  'China Officinalis',
  'Chininum Arsenicosum',
  'Chininum Sulphuricum',
  'Cicuta Virosa',
  'Cimicifuga',
  'Cina',
  'Clematis Erecta',
  'Cocculus Indicus',
  'Coffea Cruda',
  'Colchicum Autumnale',
  'Colocynthis',
  'Conium Maculatum',
  'Crataegus Oxyacantha',
  'Crocus Sativus',
  'Crotalus Horridus',
  'Croton Tiglium',
  'Cuprum Metallicum',
  'Cyclamen Europaeum',
  'Digitalis Purpurea',
  'Dioscorea Villosa',
  'Drosera Rotundifolia',
  'Dulcamara',
  'Echinacea Angustifolia',
  'Elaps Corallinus',
  'Eupatorium Perfoliatum',
  'Euphrasia Officinalis',
  'Ferrum Metallicum',
  'Ferrum Phosphoricum',
  'Fluoricum Acidum',
  'Gelsemium Sempervirens',
  'Glonoinum',
  'Graphites',
  'Grindelia Robusta',
  'Guaiacum Officinale',
  'Hamamelis Virginiana',
  'Hecla Lava',
  'Hepar Sulphuris Calcareum',
  'Hydrastis Canadensis',
  'Hydrocotyle Asiatica',
  'Hyoscyamus Niger',
  'Hypericum Perforatum',
  'Ignatia Amara',
  'Iodum',
  'Ipecacuanha',
  'Iris Versicolor',
  'Jaborandi',
  'Kali Bichromicum',
  'Kali Bromatum',
  'Kali Carbonicum',
  'Kali Iodatum',
  'Kali Muriaticum',
  'Kali Phosphoricum',
  'Kali Sulphuricum',
  'Kalmegh',
  'Kreosotum',
  'Lac Caninum',
  'Lac Defloratum',
  'Lachesis Mutus',
  'Lachnanthes Tinctoria',
  'Laurocerasus',
  'Ledum Palustre',
  'Lilium Tigrinum',
  'Lobelia Inflata',
  'Lycopodium Clavatum',
  'Lycopus Virginicus',
  'Magnesia Carbonica',
  'Magnesia Muriatica',
  'Magnesia Phosphorica',
  'Medorrhinum',
  'Melilotus Officinalis',
  'Mercurius Corrosivus',
  'Mercurius Solubilis',
  'Mezereum',
  'Millefolium',
  'Moschus',
  'Murex Purpurea',
  'Muriaticum Acidum',
  'Myristica Sebifera',
  'Naja Tripudians',
  'Natrum Carbonicum',
  'Natrum Muriaticum',
  'Natrum Phosphoricum',
  'Natrum Sulphuricum',
  'Nitricum Acidum',
  'Nux Moschata',
  'Nux Vomica',
  'Oleander',
  'Opium',
  'Oxalicum Acidum',
  'Palladium',
  'Paris Quadrifolia',
  'Petroleum',
  'Petroselinum',
  'Phosphoricum Acidum',
  'Phosphorus',
  'Phytolacca Decandra',
  'Picricum Acidum',
  'Plantago Major',
  'Platina',
  'Plumbum Metallicum',
  'Podophyllum Peltatum',
  'Psorinum',
  'Pulsatilla Nigricans',
  'Pyrogenium',
  'Ranunculus Bulbosus',
  'Ratanhia',
  'Rheum Palmatum',
  'Rhododendron',
  'Rhus Toxicodendron',
  'Robinia',
  'Rumex Crispus',
  'Ruta Graveolens',
  'Sabadilla',
  'Sabina',
  'Sambucus Nigra',
  'Sanguinaria Canadensis',
  'Sanicula Aqua',
  'Sarsaparilla',
  'Secale Cornutum',
  'Selenium Metallicum',
  'Senega',
  'Sepia Officinalis',
  'Silicea Terra',
  'Spigelia Anthelmia',
  'Spongia Tosta',
  'Stannum Metallicum',
  'Staphysagria',
  'Sticta Pulmonaria',
  'Stramonium',
  'Strophanthus',
  'Sulphur',
  'Sulphuricum Acidum',
  'Symphytum Officinale',
  'Syphilinum',
  'Tabacum',
  'Tarentula Hispanica',
  'Tellurium',
  'Terebinthina',
  'Thallium Metallicum',
  'Theridion Curassavicum',
  'Thuja Occidentalis',
  'Thyroidinum',
  'Tuberculinum',
  'Urtica Urens',
  'Ustilago Maydis',
  'Valeriana Officinalis',
  'Veratrum Album',
  'Veratrum Viride',
  'Verbascum Thapsus',
  'Vipera',
  'Zincum Metallicum',
]

export const DEFAULT_PRACTITIONER_REMEDIES = [
  'Nux Vomica',
  'Arsenicum Album',
  'Lycopodium Clavatum',
  'Natrum Muriaticum',
  'Pulsatilla Nigricans',
  'Sulphur',
  'Phosphorus',
  'Calcarea Carbonicum',
  'Sepia Officinalis',
  'Silicea Terra',
  'Belladonna',
  'Bryonia Alba',
  'Rhus Toxicodendron',
  'Apis Mellifica',
  'Arnica Montana',
  'Ignatia Amara',
  'Lachesis Mutus',
  'Mercurius Solubilis',
  'Hepar Sulphuris Calcareum',
  'Graphites',
  'Thuja Occidentalis',
  'Causticum',
  'Kali Carbonicum',
  'Staphysagria',
  'Conium Maculatum',
  'Chamomilla',
  'Ipecacuanha',
  'Aconitum Napellus',
  'Gelsemium Sempervirens',
  'Coffea Cruda',
]
