// ─────────────────────────────────────────────────────────────
// Initial seed data for new clinics.
// ─────────────────────────────────────────────────────────────
import { todayISO } from './day'
import type {
  Appointment,
  CheckIn,
  ClinicDocument,
  DoseReminder,
  Handoff,
  AppNotification,
  Outcome,
  Patient,
  Practitioner,
  Prescription,
  RemedyStock,
} from './types'

export const CLINIC = {
  name: 'Sneham Digital Clinic',
  tagline: 'Healing with compassion',
  location: 'Bandra clinic',
  otherLocations: 2,
  region: 'Mumbai',
}

// Master remedy list used across the clinic
export const REMEDY_MASTER = [
  'Nux Vomica',
  'Arsenicum Album',
  'Lycopodium',
  'Natrum Mur',
  'Pulsatilla',
  'Sulphur',
  'Belladonna',
  'Graphites',
  'Argentum Nit.',
  'Coffea Cruda',
  'Sepia',
  'Phosphorus',
  'Arnica Montana',
]

export const practitioners: Practitioner[] = [
  {
    id: 'pr-neha',
    name: 'Dr. Neha Tripathi',
    initials: 'NT',
    role: 'Owner',
    specialty: 'Chronic care',
    qualifications: 'BHMS, MD (Hom)',
    registrationNo: 'Reg. 41982',
    openCases: 48,
    remedyList: [
      'Nux Vomica',
      'Arsenicum Album',
      'Lycopodium',
      'Natrum Mur',
      'Pulsatilla',
      'Sulphur',
      'Arnica Montana',
      'Belladonna',
    ],
    rxTemplates: [],
  },
  {
    id: 'pr-ishwari',
    name: 'Dr. Ishwari Wankhade',
    initials: 'IW',
    role: 'Practitioner',
    specialty: 'Chronic · paediatrics',
    openCases: 31,
    remedyList: ['Pulsatilla', 'Chamomilla', 'Calcarea Carb', 'Nux Vomica'],
    rxTemplates: [],
  },
  {
    id: 'pr-sanjay',
    name: 'Dr. Sanjay Iyer',
    initials: 'SI',
    role: 'Practitioner',
    specialty: 'Skin · allergy',
    openCases: 44,
    remedyList: ['Graphites', 'Sulphur', 'Arsenicum Album'],
    rxTemplates: [],
  },
  {
    id: 'pr-neha-das',
    name: 'Dr. Neha Das',
    initials: 'ND',
    role: 'Practitioner',
    specialty: "Women's health",
    openCases: 19,
    remedyList: ['Sepia', 'Pulsatilla', 'Natrum Mur'],
    rxTemplates: [],
  },
]

export const patients: Patient[] = [
  {
    id: 'pt-ananya',
    wsCode: '#WS-1042',
    name: 'Ananya Rao',
    initials: 'AR',
    age: 34,
    sex: 'Female',
    location: 'Bandra',
    patientSince: 'Jun 2026',
    chiefComplaint: 'Chronic insomnia · 14 months',
    currentRemedy: 'Nux Vomica 200C',
    lastSeen: '10 Jul',
    owningPractitionerId: 'pr-neha',
    assignment: 'Mine',
    allergies: 'No allergies',
    regularMedication: 'No regular medication',
    lastOutcome: 'Partial',
  },
  {
    id: 'pt-kabir',
    wsCode: '#WS-1088',
    name: 'Kabir Nair',
    initials: 'KN',
    age: 41,
    sex: 'Male',
    location: 'Bandra',
    patientSince: 'Today',
    chiefComplaint: 'Allergic rhinitis · 3 yrs',
    currentRemedy: null,
    lastSeen: 'Today',
    owningPractitionerId: null,
    assignment: 'Unassigned',
    allergies: 'No allergies',
    regularMedication: 'None',
  },
  {
    id: 'pt-tara',
    wsCode: '#WS-0994',
    name: 'Tara Menon',
    initials: 'TM',
    age: 29,
    sex: 'Female',
    location: 'Bandra',
    patientSince: 'Apr 2026',
    chiefComplaint: 'Anxiety · palpitations',
    currentRemedy: 'Argentum Nit. 30C',
    lastSeen: '04 Jul',
    owningPractitionerId: 'pr-ishwari',
    assignment: 'Covering',
    allergies: 'No allergies',
    regularMedication: 'None',
  },
  {
    id: 'pt-rohit',
    wsCode: '#WS-0871',
    name: 'Rohit Sharma',
    initials: 'RS',
    age: 37,
    sex: 'Male',
    location: 'Bandra',
    patientSince: 'Feb 2026',
    chiefComplaint: 'Eczema · both hands',
    currentRemedy: 'Graphites 200C',
    lastSeen: '26 Jun',
    owningPractitionerId: 'pr-neha',
    assignment: 'Assigned to me',
    allergies: 'Dust',
    regularMedication: 'None',
  },
  {
    id: 'pt-meera',
    wsCode: '#WS-0620',
    name: 'Meera Iyer',
    initials: 'MI',
    age: 52,
    sex: 'Female',
    location: 'Bandra',
    patientSince: 'Nov 2025',
    chiefComplaint: 'Migraine',
    currentRemedy: 'Belladonna 200C',
    lastSeen: 'Today',
    owningPractitionerId: 'pr-neha',
    assignment: 'Mine',
    allergies: 'No allergies',
    regularMedication: 'None',
  },
  {
    id: 'pt-devan',
    wsCode: '#WS-0733',
    name: 'Devan Pillai',
    initials: 'DP',
    age: 45,
    sex: 'Male',
    location: 'Bandra',
    patientSince: 'Jan 2026',
    chiefComplaint: 'Acid reflux',
    currentRemedy: 'Lycopodium 1M',
    lastSeen: '18 Jun',
    owningPractitionerId: 'pr-neha',
    assignment: 'Assigned out',
    allergies: 'No allergies',
    regularMedication: 'Antacids (occasional)',
  },
]

export const appointments: Appointment[] = [
  {
    id: 'ap-1',
    patientId: 'pt-ananya',
    practitionerId: 'pr-neha',
    time: '10:30 AM',
    date: todayISO(),
    durationMin: 30,
    type: 'In person',
    status: 'In consult',
    tag: 'Nux Vomica 200C',
    reason: 'Chronic insomnia · review',
  },
  {
    id: 'ap-2',
    patientId: 'pt-meera',
    practitionerId: 'pr-neha',
    time: '11:15 AM',
    date: todayISO(),
    durationMin: 30,
    type: 'In person',
    status: 'Waiting',
    tag: 'Belladonna 200C',
    reason: 'Migraine · follow-up',
  },
  {
    id: 'ap-3',
    patientId: 'pt-kabir',
    practitionerId: 'pr-neha',
    time: '12:00 PM',
    date: todayISO(),
    durationMin: 30,
    type: 'In person',
    status: 'New',
    reason: 'Allergic rhinitis · first visit',
    isFirstVisit: true,
  },
  {
    id: 'ap-4',
    patientId: 'pt-tara',
    practitionerId: 'pr-neha',
    time: '02:00 PM',
    date: todayISO(),
    durationMin: 30,
    type: 'Video',
    status: 'Upcoming',
    tag: 'Argentum Nit. 30C',
    reason: 'Anxiety · follow-up',
  },
]

export const prescriptions: Prescription[] = [
  {
    id: 'rx-1',
    patientId: 'pt-ananya',
    practitionerId: 'pr-neha',
    remedy: 'Nux Vomica',
    potency: '200C',
    doseGlobules: 4,
    repetition: 'Once daily · night',
    durationDays: 14,
    preparation:
      'Dissolve under the tongue at night, 15 minutes away from food, drink or mint. Tip into the cap — don’t touch the globules.',
    publishedAt: '2026-07-10T20:00:00+05:30',
    sharedVia: ['Patient app', 'WhatsApp'],
    remindersEnabled: true,
    reminderTimes: ['8:00 AM', '8:00 PM'],
  },
  {
    id: 'rx-2',
    patientId: 'pt-ananya',
    practitionerId: 'pr-neha',
    remedy: 'Arnica Montana',
    potency: '30C',
    doseGlobules: 3,
    repetition: 'As needed',
    durationDays: null,
    preparation:
      'For muscle soreness after exercise. Take only when needed, up to three times a day.',
    publishedAt: '2026-07-10T20:05:00+05:30',
    sharedVia: ['Patient app'],
    remindersEnabled: false,
    reminderTimes: [],
  },
]

export const doseReminders: DoseReminder[] = [
  {
    id: 'dr-1',
    prescriptionId: 'rx-1',
    patientId: 'pt-ananya',
    remedy: 'Nux Vomica',
    potency: '200C',
    time: '8:00 AM',
    slot: 'Morning',
    loggedToday: true,
  },
  {
    id: 'dr-2',
    prescriptionId: 'rx-1',
    patientId: 'pt-ananya',
    remedy: 'Nux Vomica',
    potency: '200C',
    time: '8:00 PM',
    slot: 'Evening',
    loggedToday: false,
  },
]

export const checkIns: CheckIn[] = [
  {
    id: 'ci-1',
    patientId: 'pt-ananya',
    prescriptionId: 'rx-1',
    improvementPct: 65,
    changeChips: ['Sleeping longer', 'Calmer mornings', 'Still waking once'],
    freeText: 'Falling asleep faster than before. Still wake once around 4am but settle again.',
    submittedAt: '2026-07-08T09:20:00+05:30',
    marked: 'better',
  },
]

export const handoffs: Handoff[] = [
  {
    id: 'ho-1',
    patientId: 'pt-rohit',
    fromPractitionerId: 'pr-sanjay',
    toPractitionerId: 'pr-neha',
    coveringUntil: '02 Aug',
    note: {
      currentRemedy: 'Graphites 200C',
      caseStatus: 'Partial improvement — skin drier, less cracking.',
      reason: 'Dr. Sanjay is on leave this week.',
      watchFor: 'Do not repeat before 30 Jul. Sensitive: recent bereavement.',
    },
    status: 'pending',
    patientNotified: false,
  },
]

export const documents: ClinicDocument[] = [
  { id: 'doc-1', patientId: 'pt-ananya', name: 'Prescription · 10 Jul', kind: 'Prescription', format: 'PDF', size: '92 KB', date: '10 Jul 2026', uploadedBy: 'practitioner' },
  { id: 'doc-2', patientId: 'pt-ananya', name: 'Thyroid panel', kind: 'Report', format: 'PDF', size: '210 KB', date: '20 Jun 2026', uploadedBy: 'patient' },
  { id: 'doc-3', patientId: 'pt-ananya', name: 'Invoice #WS-4471', kind: 'Invoice', format: 'PDF', size: '48 KB', date: '10 Jul 2026', uploadedBy: 'practitioner' },
]

export const remedyStock: RemedyStock[] = [
  { name: 'Nux Vomica', potency: '200C', qty: 12, low: false },
  { name: 'Arnica Montana', potency: '30C', qty: 3, low: true },
  { name: 'Lycopodium', potency: '1M', qty: 9, low: false },
  { name: 'Graphites', potency: '200C', qty: 2, low: true },
]

export const outcomes: Outcome[] = [
  { id: 'oc-1', patientId: 'pt-ananya', practitionerId: 'pr-neha', date: '2026-07-10', remedy: 'Nux Vomica 200C', outcome: 'Partial', note: 'Repeat. Sleep onset improved, still waking at 3am.' },
  { id: 'oc-2', patientId: 'pt-ananya', practitionerId: 'pr-neha', date: '2026-06-12', remedy: 'Nux Vomica 200C', outcome: 'Clear improvement', note: 'First prescription. Marked calming within the first week.' },
  { id: 'oc-3', patientId: 'pt-ananya', practitionerId: 'pr-neha', date: '2026-06-02', remedy: 'Coffea Cruda 30C', outcome: 'No change', note: 'Trial for racing mind — no clear response.' },
]

export const notifications: AppNotification[] = [
  {
    id: 'nf-1',
    surface: 'web',
    kind: 'handoff',
    title: 'Handoff pending — Rohit Sharma',
    message: 'Dr. Sanjay Iyer has asked you to cover this case until 02 Aug.',
    time: '9 min ago',
    read: false,
    severity: 'purple',
    pending: true,
    patientId: 'pt-rohit',
  },
  {
    id: 'nf-2',
    surface: 'web',
    kind: 'booking',
    title: 'New booking — Priya S.',
    message: 'Video consult requested for Thu 30 Jul, 3:30 PM.',
    time: '22 min ago',
    read: false,
    severity: 'info',
  },
  {
    id: 'nf-3',
    surface: 'web',
    kind: 'low_stock',
    title: 'Low stock — Arnica Montana 30C',
    message: 'Only 3 vials left at the Bandra clinic.',
    time: '1 hr ago',
    read: true,
    severity: 'warn',
  },
]
